name: Build and Publish Python GPU Bindings (linux only)


on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to release"
        required: true
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: .

jobs:

  linux:
    permissions:
      contents: read
      packages: write
    runs-on: GPU
    strategy:
      matrix:
        target: [x86_64]
    env:
      RELEASE_TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  #v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa  #v4.8.0
        with:
          python-version: 3.12
          architecture: x64

      - name: Set pyproject.toml version to match github tag
        shell: bash
        run: |
            mv pyproject.toml pyproject.toml.orig
            sed "s/ezkl/ezkl-gpu/" pyproject.toml.orig >pyproject.toml
            sed "s/0\\.0\\.0/${RELEASE_TAG//v}/" pyproject.toml.orig >pyproject.toml

      - uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f  #v1.0.6
        with:
          toolchain: nightly-2023-06-27
          override: true
          components: rustfmt, clippy

      - name: Set Cargo.toml version to match github tag
        shell: bash
        run: |
          mv Cargo.toml Cargo.toml.orig
          sed "s/0\\.0\\.0/${RELEASE_TAG//v}/" Cargo.toml.orig >Cargo.toml
          mv Cargo.lock Cargo.lock.orig
          sed "s/0\\.0\\.0/${RELEASE_TAG//v}/" Cargo.lock.orig >Cargo.lock

      - name: Install required libraries
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y openssl pkg-config libssl-dev

      - name: Build wheels
        uses: PyO3/maturin-action@5f8a1b3b0aad13193f46c9131f9b9e663def8ce5  #v1.46.0
        with:
          target: ${{ matrix.target }}
          manylinux: auto
          container: off
          args: --release --out dist --features python-bindings,icicle

      - name: Install built wheel
        if: matrix.target == 'x86_64'
        run: |
          pip install ezkl-gpu --no-index --find-links dist --force-reinstall

      - name: Upload wheels
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5  #v3.2.1
        with:
          name: wheels
          path: dist


  pypi-publish:
    name: Uploads release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: "startsWith(github.ref, 'refs/tags/')"
    # TODO: Uncomment if linux-cross is working
    # needs: [ macos, windows, linux, linux-cross, musllinux, musllinux-cross ]
    needs: [linux]
    steps:
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a  #v3.0.2
        with:
          name: wheels
      - name: List Files
        run: ls -R

      # Both publish steps will fail if there is no trusted publisher setup
      # On failure the publish step will then simply continue to the next one

      # publishes to PyPI
      - name: Publish package distributions to PyPI
        continue-on-error: true
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  #v1.12.4
        with:
          packages-dir: ./

      # publishes to TestPyPI
      - name: Publish package distribution to TestPyPI
        continue-on-error: true
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  #v1.12.4
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: ./
