name: Bump Version

on:
  push:
    branches: ["main"]

jobs:
  bump-version:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    permissions:
      contents: write
=======
>>>>>>> f4dddd60e564a128e740dbbff1d026a37e8e8984

    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}